language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nosetests
env:
  global:
    secure: Bc0MheER2mdqdSYWmxahChMV7Tqq9GzdeTydR+Hr8iCStD3bXdoh8gSSBZV3AacZJxPn4agt0N7zTI9CoeplTXxSlcS6yKC7YCDO0lW2NyoAJ7SexVWB1QUpWhPTGJ1RJ/MIZMsFjjPTvkVJXgC5oroGzXnoqWnuCHVINKHuQxWCVfSOC+Negy+N1gZZ7YeBFhsjS5IOE/kuNQLx30fJHjHB1k5kHflUbOgRoUjRt8CtVvYq7obhYYI+3PMuyPWpwBsM/sRNN6y6AfaN2rx1Bbmiaq3YueObbCmw+b1OF40PmwPKt6QDvJKh8yW46vmoHhLVL8hbu4FGulze5axqjz4lYt4iQ6gRJgdIWZRCaJYA8gTqbZ4JtkzIRis5KyqRt7Hlkuhh5LtAQZ5Uy30tMmzdkN6/SKh68Hf0Fwa7yiI+CKM/oGGZZQ3CgslB1iN9E/4396hYGy1311rjCBvB/+MN7GWplcnWkDexd7QZom8dSJuTFsqD2Q9SHnmTUlX/9sfgwTF0jo1WpDdse++nL4NAju3OBw1VmxKcHUOtGXMEjs/whasiq8FTilYJYG7HfbLbspi0bCEhHWfcrCUtQ4l3pSo4roD3DB30bgqmIKVb7Wo+xWVRlo3+xZ4D5UFKm0XmH6A3RBxYFRco69UDa7Iosuwbv69dzzLfs+aAqE4=
