language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nosetests
env:
  global:
    secure: I8tfkuViE8pVgcbzhgwClBuR0HYAN0H+KiXuL8kfwgrMTzr9g44bKyqPwbp3jogK5I9v1MCV7k15zkoZM6Laww75e+v0jdGPPjpMiWx2ohhzUT2u2DKeJsywL/5pajypXbLhFWlHk9AZUScs279kwkyCmPlBNMxxN0k45cNk278dncxskZ9u6iXnXZ7ev+7/Gmu2MahDp20V5BeZZkwTPMpxmAz5ntpMmCia13DD8RzZeQqv1sr/I+nOjp8Gvo98drKku2tBaV5TCPNx+POuNCLl1pb+kq0ZuMvNFN23okq89QAnFWk4SnSjn2f3CddjHyf7Z5+9tkduU6r2B1WVGIjD0aeDezSW3TyKIXbel5+z9XmHOon1Zjam7kOhX2GGc7Ch5h2pL6sIg9T+B8iKORU/Z13cJmi1i68YhwbDTXZmbhj7rhCW0vD5NlkHrEJkQbddlpr83o+ZsE9V0fWiZlrQXE/bFaDgFbtntEbrvn+xK5EI/H9szLJsiJxaOvJxAfCdP34uFS2HtesMSaAjPbLsMUeFcIQbFYXa3yzBjecVnCVdTJdXZnsaMIj4nCiqhLcwyHoR7zvgLpZ0Bon49yL1WCmBNPpQRYIm3gARmAQIe4fukCSs/GL+QaJE6JEUDXofYwmbZuVH9u4d5kAt7cUi4aNEjLGuzTCrn9x+E4Q=
